name: Android CI and Release

on: # Run whenever push to main or pr to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger

jobs:
  test_job:
    runs-on: ubuntu-latest
    # Required to create Releases and upload Assets
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4 # Install Java
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Run Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: "**/build/reports/tests/testDebugUnitTest/"

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.jks

      - name: Verify Versioning
        run: ./gradlew :app:printVersionInfo

      - name: Extract Version Name
        id: get_version
        run: |
          VERSION_NAME=$(./gradlew -q :app:printVersionName)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Build Release Bundle & APK
        run: ./gradlew bundleRelease assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        env:
          DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}

      - name: Upload Artifacts to Actions Tab
        uses: actions/upload-artifact@v4
        with:
          name: Mintanable-Builds-v${{ steps.get_version.outputs.VERSION_NAME }}
          path: |
            app/build/outputs/apk/*/NoteThePad-*.apk
            app/build/outputs/bundle/*/NoteThePad-*.aab

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION_NAME }}
          name: Release v${{ steps.get_version.outputs.VERSION_NAME }}
          files: |
            app/build/outputs/apk/release/NoteThePad-*.apk
            app/build/outputs/bundle/release/NoteThePad-*.aab
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}