name: Android Unit Tests

on: # Run whenever push to main or pr to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  #for manual trigger

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4 # Install Java
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Build App
        run: ./gradlew assembleDebug
        env:
          DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}