name: Android Unit Tests

on: # Run whenever push to main or pr to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  #for manual trigger

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4 # Install Java
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Run Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.jks

      - name: Verify Versioning
        run: ./gradlew printVersionInfo

      - name: Build Release Bundle & APK
        run: ./gradlew bundleRelease assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        env:
          DRIVE_CLIENT_ID: ${{ secrets.DRIVE_CLIENT_ID }}
          DRIVE_CLIENT_SECRET: ${{ secrets.DRIVE_CLIENT_SECRET }}


      - name: Upload Release Bundle (AAB)
        uses: actions/upload-artifact@v4
        with:
          name: Mintanable-Release-Bundle
          path: app/build/outputs/bundle/release/*.aab

      - name: Upload Release APK (Signed)
        uses: actions/upload-artifact@v4
        with:
          name: Mintanable-Release-APK
          path: app/build/outputs/apk/release/NoteThePad-*.apk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Mintanable-Debug-APK
          path: app/build/outputs/apk/debug/NoteThePad-*.apk